spring.application.name=EmployeeManagementSystem-ProjectUsingSpringBoot
# 1. Database Connection (URL, Username, Password)
spring.datasource.url=jdbc:mysql://localhost:3306/EMPApplication
spring.datasource.username=root
spring.datasource.password=root

# 2. Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081